[package]
name = "github-webhook-notification"
version = "0.0.2"
edition = "2021"

[dependencies]
clap = "2"
actix = "0.11.0-beta.2"
actix-web = "4.0.0-beta.3"
actix-rt = "2.0.2"
teloxide = "0.5"
teloxide-macros = "0.4"
anyhow = "1"
serde_json = "1"
toml = "0.5"
env_logger = "0.8"
serde_derive = "1"
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
tokio = { version = "1", features = ["full"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }